willow/app/views/records/edit_fields/_rights.html.erb

Replace part of the Sufia gem equivalent of the New Work page with an app local one.

Add the missing file to make to the New Work page load

---

willow/Dockerfile

Install libreoffice

---

willow/Dockerfile_production
willow/startup_prod.sh

Add Docker cloud specific config

---

willow/Dockerfile_production

make Java version changes to willow production Dockerfile as well

---

willow/app/views/_masthead.html.erb

Include necessary partial in masthead

---

willow/app/views/sufia/admin/stats/_deposits.html.erb

Modify the deposists partial to handle nil users

---

willow/lib/sufia/configuration.rb

Revert to default Sufia banner image

---

willow/app/assets/stylesheets/sufia.scss
willow/app/assets/stylesheets/willow.scss
willow/app/views/layouts/homepage.html.erb
willow/app/views/sufia/homepage/_marketing.html.erb

Remove banner and text box from header, move text to welcome box, change welcome box style

---

willow/app/assets/stylesheets/application.css

Remove CL colour scheme, revert to default colours

---

willow/app/views/sufia/admin_sets/_seach_form.html.erb

Update placeholder text

---

willow/app/assets/stylesheets/willow.scss

this has been driving me nuts for ages.  Just some wonky styles in sufia, I have provided an override in our own css.

add new style to fix floating save box display bug

---

docker-compose.yml
willow/Dockerfile
willow/config/initializers/sufia.rb
willow/docker-entrypoint.sh

also, verify Solr is running before running Willow

Store derivatives in volume

---

willow/app/models/dataset.rb
willow/spec/models/dataset_spec.rb

Fixes issue https://github.com/CottageLabs/willow/issues/177

Removed required validation for DOI from model

---

willow/app/models/ability.rb

Ensure admins have all roles

---

willow/Dockerfile
willow/Gemfile
willow/app/assets/javascripts/nested_field_manager.js
willow/config/initializers/sufia_notifications.rb

* Ensure the generated Gemfile.lock is not overwritten
* Convert nested field manager js to ES5
* Fix issue with notifications library not loading

Bug fixes for production

---

willow/app/controllers/concerns/hyrax/notifications/notifiers.rb
willow/lib/hyrax/notifications/subscribers/build_message.rb
willow/lib/hyrax/notifications/subscribers/kinesis.rb
willow/lib/hyrax/notifications/subscribers/subscriber.rb
willow/spec/messages/controllers/articles_controller_spec.rb
willow/spec/messages/controllers/books_controller_spec.rb
willow/spec/messages/controllers/datasets_controller_spec.rb
willow/spec/messages/controllers/images_controller_spec.rb

Change messageType in header to match JISC spec

---

willow/app/assets/javascripts/application.js
willow/app/assets/javascripts/collections-csrf-bugfix.js

Workaround for bug adding work to collection

---

willow/config/initializers/hyrax.rb

Does not resolve dates coming directly from Solr in YYYY-MM-DD format.
#224

Partial fix for date format

---

README.md
example.env.development
example.env.production
willow/config/initializers/action_mailer.rb
willow/config/initializers/hyrax.rb
willow/config/initializers/mailboxer.rb

(Oops, also add Google Analytics ID support. Should've been a separate PR but I modified the same hyrax initialiser as the email stuff, so it sneaked in.)

Add SMTP configuration support to Willow

---

willow/app/models/hyrax/contact_form.rb

Review and merge #236 first, it will make this PR much much smaller.
For issue #225

Override Hyrax's ContactForm, allowing any message to be received regardless of the user's email

---

README.md
example.env.production
willow/config/initializers/devise.rb

Review and merge #236 first, it will make this PR much much smaller.
For issue #225

Allow setting an ENV var to fix the forgotten password form

---

README.md
example.env.production
willow/config/initializers/hyrax.rb

add BATCH_USER and AUDIT_USER config env vars

---

willow/config/initializers/hyrax.rb

store derivatives where we already have a defined volume + ability to config via env var

---

willow/lib/data_importer/importer.rb
willow/lib/hyrax/notifications/subscribers/build_message.rb
willow/lib/tasks/seed_test_data.rake

Ensure files are characterized on load, ensure filesize is integer
